var/redmine_home/plugins/redmine_favorite_projects/config/routes.rb
#custom routes for this plugin

resources :favorite_project_queries

match "favorite_projects/favorite" => "favorite_projects#favorite", :via => [:post]
match "favorite_projects/unfavorite" => "favorite_projects#unfavorite", :via => [:delete]

match "favorite_projects/search" => "favorite_projects#search", :as => "search_favorite_projects", :via => [:get, :post]

match 'auto_completes/project_tags' => 'auto_completes#project_tags', :via => :get, :as => 'auto_complete_project_tags'

var/redmine_home/plugins/redmine_favorite_projects/app/controllers/favorite_project_queries_controller.rb
class FavoriteProjectQueriesController < ApplicationController
  before_filter :find_query, :except => [:new, :create, :index]

  accept_api_auth :index

  helper :queries
  include QueriesHelper
  
  before_filter do
    unless(User.current.allowed_to?(:manage_public_favorite_project_queries, nil, :global => true) || User.current.allowed_to?(:manage_favorite_project_queries, nil, :global => true))      
      deny_access
    end
  end

  def index
    case params[:format]
    when 'xml', 'json'
      @offset, @limit = api_offset_and_limit
    else
      @limit = per_page_option
    end
    @query_count = FavoriteProjectsQuery.visible.count
    @query_pages = Paginator.new @query_count, @limit, params['page']
    @queries = FavoriteProjectsQuery.visible.
                    order("#{Query.table_name}.name").
                    limit(@limit).
                    offset(@offset).
                    all
    respond_to do |format|
      format.html
      format.api
    end
  end

  def new
    @query = FavoriteProjectsQuery.new
    @query.user = User.current

    unless User.current.allowed_to?(:manage_public_favorite_project_queries, nil, :global => true) || User.current.admin?
      @query.visibility = FavoriteProjectsQuery::VISIBILITY_PRIVATE
    end

    @query.build_from_params(params)
  end

  def create
    @query = FavoriteProjectsQuery.new(params[:query])
    @query.user = User.current

    @query.build_from_params(params)

    unless User.current.allowed_to?(:manage_public_favorite_project_queries, nil, :global => true) || User.current.admin?
      @query.visibility = FavoriteProjectsQuery::VISIBILITY_PRIVATE
    end

    @query.column_names = nil if params[:default_columns]

    if @query.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to url_for({:controller => "favorite_projects", :action => "search", :query_id => @query.id})
    else
      render :action => 'new', :layout => !request.xhr?
    end
  end

  def edit
  end

  def update
    @query.attributes = params[:query]
    @query.build_from_params(params)

    unless User.current.allowed_to?(:manage_public_favorite_project_queries, nil, :global => true) || User.current.admin?
      @query.visibility = FavoriteProjectsQuery::VISIBILITY_PRIVATE
    end

    @query.column_names = nil if params[:default_columns]

    if @query.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to url_for({:controller => "favorite_projects", :action => "search", :query_id => @query.id})
    else
      render :action => 'edit'
    end
  end

  def destroy
    @query.destroy
    redirect_to url_for({:controller => "favorite_projects", :action => "search", :set_filter => 1})
  end

private

  def find_query
    @query = FavoriteProjectsQuery.find(params[:id])
    render_403 unless @query.editable_by?(User.current)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

end

var/redmine_home/plugins/redmine_favorite_projects/app/views/favorite_project_queries/_form.html.erb
<%= error_messages_for 'query' %>

<div class="box">
  <div class="tabular">
    <%= hidden_field_tag 'gantt', '1' if params[:gantt] %>

    <p><label for="query_name"><%=l(:field_name)%></label>
    <%= text_field 'query', 'name', :size => 80 %></p>

    <% if User.current.admin? || User.current.allowed_to?(:manage_public_favorite_project_queries, nil, :global => true) %>
      <p><label><%=l(:field_visible)%></label>
        <label class="block"><%= radio_button 'query', 'visibility', FavoriteProjectsQuery::VISIBILITY_PRIVATE %> <%= l(:label_visibility_private) %></label>
        <label class="block"><%= radio_button 'query', 'visibility', FavoriteProjectsQuery::VISIBILITY_PUBLIC %> <%= l(:label_visibility_public) %></label>
      </p>
    <% end %>


    <fieldset><legend><%= l(:label_options) %></legend>
    <p><label for="query_default_columns"><%=l(:label_default_columns)%></label>
    <%= check_box_tag 'default_columns', 1, @query.has_default_columns?, :id => 'query_default_columns',
          :onclick => 'if (this.checked) {$("#columns").hide();} else {$("#columns").show();}' %></p>
    </fieldset>
  </div>

  <fieldset id="filters"><legend><%= l(:label_filter_plural) %></legend>
  <%= render :partial => 'queries/filters', :locals => {:query => query}%>
  </fieldset>

  <%= content_tag 'fieldset', :id => 'columns', :style => (query.has_default_columns? ? 'display:none;' : nil) do %>
  <legend><%= l(:field_column_names) %></legend>
  <%= render_query_columns_selection(query) %>
  <% end %>

  </div>

<%= javascript_tag do %>
$(document).ready(function(){
  $("input[name='query[visibility]']").change(function(){
    var checked = $('#query_visibility_1').is(':checked');
    $("input[name='query[role_ids][]'][type=checkbox]").attr('disabled', !checked);
  }).trigger('change');
});
<% end %>

var/redmine_home/plugins/redmine_favorite_projects/app/views/favorite_project_queries/edit.html.erb
<h2><%= l(:label_query) %></h2>

<%= form_tag(favorite_project_query_path(@query), :method => :put) do %>
  <%= render :partial => 'favorite_project_queries/form', :locals => {:query => @query} %>
  <%= submit_tag l(:button_save) %>
<% end %>

var/redmine_home/plugins/redmine_favorite_projects/app/views/favorite_project_queries/index.html.erb
<div class="contextual">
<% if User.current.allowed_to?(:manage_favorite_project_queries, nil , :global => true) %>
<%= link_to l(:label_query_new), { :controller => 'favorite_project_queries', :action => 'new' }, :class => 'icon icon-add'  %>
<% end %>
</div>

<h2><%= l(:label_query_plural) %></h2>
<% if @queries.empty? %>
  <p><i><%=l(:label_no_data)%></i></p>
<% else %>
  <table class="list">
  <% @queries.each do |query| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td class="name">
        <%= link_to h(query.name), :controller => "favorite_projects", :action => 'search', :query_id => query %>
      </td>
      <td class="buttons">
        <% if query.editable_by?(User.current) %>
        <%= link_to l(:button_edit), edit_favorite_project_query_path(query), :class => 'icon icon-edit' %>
        <%= delete_link favorite_project_query_path(query) %>
      <% end %>
      </td>
    </tr>
  <% end %>
  </table>
<% end %>

var/redmine_home/plugins/redmine_favorite_projects/app/views/favorite_project_queries/new.html.erb
<h2><%= l(:label_query_new) %></h2>

<%= form_tag(favorite_project_queries_path) do %>
  <%= render :partial => 'favorite_project_queries/form', :locals => {:query => @query} %>
  <%= submit_tag l(:button_save) %>
<% end %>